# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: docker
    directory: /cmd/cloudstack-csi-sc-syncer
    labels:
      - dependencies
      - docker
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: docker
    directory: /cmd/cloudstack-csi-driver
    labels:
      - dependencies
      - docker
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
