apiVersion: v1
kind: Pod
metadata:
  name: example-pod-from-snapshot-data
spec:
  containers:
    - name: example
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: example-volume
      stdin: true
      stdinOnce: true
      tty: true
  volumes:
    - name: example-volume
      persistentVolumeClaim:
        claimName: pvc-from-snapshot