apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: example-snapshot
spec:
  volumeSnapshotClassName: csi-cloudstack-snapclass
  source:
    persistentVolumeClaimName: example-pvc