apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.cloudstack.apache.org
spec:
  attachRequired: true
  podInfoOnMount: false
  # Supports only persistent volumes.
  volumeLifecycleModes:
    - Persistent
