{{- if and (.Values.secret.create) (.Values.secret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "cloud.conf" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudstack-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  cloud-config: {{ include "cloudConfig" . | b64enc }}
{{- end }}