{{ if .Values.syncer.enabled }}
{{ if .Values.syncer.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.syncer.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudstack-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.syncer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.syncer.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.syncer.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-sc-syncer-role
  labels:
    {{- include "cloudstack-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "create", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-sc-syncer-binding
  labels:
    {{- include "cloudstack-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.syncer.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-sc-syncer-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}