apiVersion: v2
name: cloudstack-csi
description: A Helm chart for CloudStack CSI driver
type: application
version: 2.0.0
appVersion: 0.6.0
sources:
  - https://github.com/Leaseweb/cloudstack-csi-driver
keywords:
  - csi
  - cloudStack
